version: "3.3"
services:
  nginx:
    ports:
      - "8000:80"
  qrate-backend:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node server.js
